// <auto-generated />
using System;
using Firefighters.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Firefighters.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190804230606_VamosLoco")]
    partial class VamosLoco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Firefighters.Web.Data.Entities.Area", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Firefighters.Web.Data.Entities.Elemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo");

                    b.Property<short?>("AreaId");

                    b.Property<DateTime?>("BajaFecha");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CompraFecha");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("FabricacionFecha");

                    b.Property<short>("IdEstado");

                    b.Property<short>("IdTitular");

                    b.Property<string>("Marca")
                        .HasMaxLength(50);

                    b.Property<string>("Modelo")
                        .HasMaxLength(50);

                    b.Property<string>("NroSerie")
                        .HasMaxLength(50);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500);

                    b.Property<short?>("UbicacionId");

                    b.Property<DateTime?>("VencimientoFecha");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Elementos");
                });

            modelBuilder.Entity("Firefighters.Web.Data.Entities.Ubicacion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UbicacionElemento")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Ubicacions");
                });

            modelBuilder.Entity("Firefighters.Web.Data.Entities.Elemento", b =>
                {
                    b.HasOne("Firefighters.Web.Data.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("Firefighters.Web.Data.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");
                });
#pragma warning restore 612, 618
        }
    }
}
